services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: $PGUSER
      POSTGRES_PASSWORD: $PGPASS
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: $DBNAME
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./pgdata
        target: /var/lib/postgresql/pgdata
